<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="demo.aspx.cs" Inherits="ServerInformationAnalysis.demo" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<!-- XHTML validation -->
<html xmlns="http://www.w3.org/1999/xhtml" lang="en">

<!-- HEAD tag -->
<head id="Head1" runat="server">
    <!-- Meta tags -->
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <meta name="description" content=""/>
    <meta name="author" content=""/>

    <!-- Web Page Title -->
    <title> Server Information Analysis </title>

    <!-- Bootstrap Core CSS  -->
    <link href="Content/bootstrap.min.css" rel="stylesheet" />

    <!-- Custom CSS -->
    <link href="Content/myCSS.css" rel="stylesheet" />

    <!-- Custom Fonts -->   
    <link href="font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
    <link href="http://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css"/>
    <link href="http://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic" rel="stylesheet" type="text/css"/>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
    <script type="text/javascript">
        function errorAlert(errorMessage)
        {
            console.log(errorMessage);
            alert(errorMessage);
        }
    </script>
</head>

<!-- Body starts -->
<body id="page-top" class="index">

    <!-- Navigation Bar -->
    <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <!-- Company Name -->
              <a class="navbar-brand" href="#page-top">Fluor Daniel India Pvt. Ltd.</a>
            </div>
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li class="hidden">
                        <a href="#page-top"></a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container-fluid -->
    </nav>

    <div class="container">
       
       <br /><br /><br />
        <a class="nav navbar-right" href="index.aspx" >
            <!-- Company Logo --> 
             <img id="logo" class="img-responsive" src="images/logo.jpg" alt="Fluor Logo"/> 
        </a>
           <br /><br /><br /><br /><br /><br /><br /><br />
        
    
        <!-- About the webPage -->
        <div class="jumbotron">
            <div class="container">
                

                <div class="row text-center">
                    <div class="col-xs-12 col-sm-3 col-sm-push-9">
                        <img class="img-responsive" src="images/demo1.png" />
                    </div>
                    <div class="col-xs-12 col-sm-9 col-sm-pull-3">
                        <div class="col-xs-12"> <h2> Live Preview </h2><hr class="star-light" /></div><br /><br /><br /><br /><br /><br /><br />
                        <div class="col-xs-12">
                            <h4> 
                                Check the status of the server at this very point of time. 
                            </h4>
                        </div>
                    </div>
                </div>

            </div>
        
        </div>
        <br /><br />
        <div id="main" class="jumbotron">
            
        <!-- Main form starts -->
        <form id="form1" runat="server">
            <br />
                <!-- Heading -->

                <div class="row text-center text-capitalize">

                     <h3> Servers</h3>
                     <hr class="star-light" />
                     <h5> Select the servers for their live analysis </h5>

                </div>

                <div class="row">
                    <div class="col-lg-12">
                        <!-- GridView to show the file in an order with a dropdown list individually for it-->
                        <!--
                        <asp:GridView ID="ServerList_GridView1" runat="server" align="center" CssClass="fileTable" ShowFooter="false" ShowHeader="false" AutoGenerateColumns="false" AutoGenerateDeleteButton="false" AutoGenerateEditButton="false" AutoGenerateSelectButton="false" EmptyDataText="No Servers To analyse !!!">
                            <Columns>
                                <asp:TemplateField HeaderText="Select">
                                    <ItemTemplate>
                                        <asp:RadioButton ID="selectRow" runat="server" />
                                    </ItemTemplate>
                                </asp:TemplateField>
                                <asp:BoundField DataField="Server_Name" HeaderText="Server Name" ItemStyle-Width="350" />
                            </Columns>
                        </asp:GridView>
                        -->
                        <asp:RadioButtonList ID="RadioButtonsServerList" runat="server">
                        </asp:RadioButtonList>
                    </div>
                    <div class="col-lg-12">
                        <asp:Button ID="Button1" runat="server" Text="Show" CssClass="btn btn-warning" 
                            onclick="fillView" />
                    </div>
                </div>

                <div class="row text-center text-capitalize">

                     <h2> Query Output Information </h2>
                     <hr class="star-light" />

                </div>

                <br /><br />

                <asp:Panel ID="InfoCollector" runat="server">
                </asp:Panel>

                <div class="row text-center" >
                    <asp:Button ID="ExportButton" CssClass="btn btn-outline exportBtnCss" runat="server" Text="Export to Excel" onclick="ExportExcel" Visible="False" />
                </div>
        </form>
        <br /><br />
        <div class="row text-center">
            
            <div class="col-xs-12">
                <a href="index.aspx">
                    <button type="button" class="btn btn-default">
                      <span class="glyphicon glyphicon-home"></span> Home
                    </button>
                </a>
            </div>
            
        </div>

       </div>
            
    </div>
        
         <!--#include virtual="footer.html"-->
    
        <!-- jQuery -->
        <script type="text/javascript" src="Script/jquery.js"></script>
        <script type="text/javascript" src="Script/bootstrap.min.js"></script>
        <script type="text/javascript">
            $("tbody").addClass("table table-striped table-bordered table-hover");
            $("table").parent().addClass("table-responsive");
        </script>
     </body>
</html>
