<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="index.aspx.cs" Inherits="WebApplication1.WebForm1" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<!-- XHTML validation -->
<html xmlns="http://www.w3.org/1999/xhtml" lang="en">

<!-- HEAD tag -->
<head runat="server">
    <!-- Meta tags -->
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <meta name="description" content=""/>
    <meta name="author" content=""/>

    <!-- Web Page Title -->
    <title> Server Information Analysis </title>

    <!-- Bootstrap Core CSS  -->
    <link href="Content/bootstrap.min.css" rel="stylesheet" />

    <!-- Custom CSS -->
    <link href="Content/myCSS.css" rel="stylesheet" />

    <!-- Custom Fonts -->   
    <link href="font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
    <link href="http://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css"/>
    <link href="http://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic" rel="stylesheet" type="text/css"/>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->




    <!--  The JavaScript Global Variables for Charts -->
    <script type="text/javascript">
        
    </script>

    <!--Load the Google Charts API-->
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <!-- Custom JS for Charts  -->
    <script type="text/javascript" src="Script/myJS_1.js"></script>

</head>

<!-- Body starts -->
<body id="page-top" class="index">
    
    
    <!-- Navigation Bar -->
    <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <!-- Company Name -->
              <a class="navbar-brand" href="#">Fluor Daniel India Pvt. Ltd.</a>
            </div>
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li class="hidden">
                        <a href="#page-top"></a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container-fluid -->
    </nav>


    <div class="container">
        <br /><br /><br />
        <a class="nav navbar-right" href="#page-top" >
            <!-- Company Logo --> 
             <img id="logo" class="img-responsive" src="images/logo.jpg" alt="Fluor Logo"/> 
        </a>
           <br /><br /><br /><br /><br /><br /><br /><br />
        
        <!-- About the webPage -->
        <div class="jumbotron">
            <div class="container">
            
                <h2>Server Information Analysis </h2>
                <br />
                <h4>This site with show the analytic charts of the Server Information available.</h4>

            </div>
        
        </div>
        <br /><br />
        <!-- jQuery -->
        <script type="text/javascript" src="Script/jquery.js"></script>


        <br /><br />

        <!-- Main form starts -->
        <form id="form1" runat="server">
            <br />
            <div id="main" class="jumbotron">
                <!-- Heading -->
                <div class="row">
                    <div class="col-lg-12 text-center">
                        <h2>Analysis</h2>
                        <hr class="star-light" />
                    </div>
                </div>
                <br /><br />
                <div class="container">
                <div class="row">
                    <div class="col-lg-12 text-center">
                        <!-- GridView to show the file in an order with a dropdown list individually for it-->
                        <asp:GridView ID="GridView1" runat="server" align="center" CssClass="fileTable" ShowFooter="false" ShowHeader="false" AutoGenerateColumns="false" AutoGenerateDeleteButton="false" AutoGenerateEditButton="false" AutoGenerateSelectButton="false">
                            <Columns>
                                <asp:TemplateField>
                                    <ItemTemplate>
                                        <asp:CheckBox ID="chkRow" runat="server" />
                                    </ItemTemplate>
                                </asp:TemplateField>
                                <asp:BoundField DataField="Name" HeaderText="Name" ItemStyle-Width="350" />
                                <asp:BoundField DataField="FullPath" HeaderText="FullPath"  ItemStyle-Width="150" Visible="false" />
                                <asp:TemplateField HeaderText="GraphType" ItemStyle-Width="250">
                                    <ItemTemplate>
                                        <asp:DropDownList ID="ChartList" runat="server" CssClass="form-control" disabled="true" >
                                            <asp:ListItem Text="BarChart" Value="1"></asp:ListItem>
                                            <asp:ListItem Text="LineChart" Value="2"></asp:ListItem>
                                            <asp:ListItem Text="PieChart" Value="3"></asp:ListItem>
                                            <asp:ListItem Text="XY-Scatter Chart" Value="4"></asp:ListItem>
                                            <asp:ListItem Text="Donut Chart" Value="5"></asp:ListItem>
                                        </asp:DropDownList>
                                    </ItemTemplate>
                                </asp:TemplateField>
                            </Columns>
                        </asp:GridView>
                        </div>
                    </div>
                    <br /><br />
                    <!-- Bootstrap class -->
                    <div class="row">
                        <!-- Bootstrap class -->
                        <div class="col-lg-12 text-center">
                            <!-- Asp.net button for starting the process of reading the xml files and analysing it on clicking it,by calling 'analyseClick()' method defined in it CodeBehind file. -->
                            <asp:Button ID="Button1" runat="server" Text="Analyse" OnClick="analyseClick" CssClass="btn btn-info" />
                        </div>
                    </div>
                    <br /><br /><br />
                    
                    <!-- For showing charts on the mainWindow. These will be static. -->
                    <div id="mainWindowCharts">
                    </div>

                    <!-- This Asp panel will become a div when converted to HTML and will hold Hidden Fields which will be having the information fetched from the XML files -->
                    <asp:Panel ID="Charts_Info" runat="server"></asp:Panel>
                <!-- End OF Container -->
                </div>
                <br /><br />
                <!-- End of Main Jumbotron -->
            </div>
        
            <!-- JavaScript file having the function which will parse the information recieved and start the process -->
            <script type="text/javascript" src="Script/myJS_2.js"></script>
     
        
        <!-- Bootstrap Core JavaScript -->
    <script type="text/javascript" src="Script/bootstrap.min.js"></script>
    <!-- Plugin JavaScript -->
    <script src="Script/classie.js"></script>
    <script src="Script/cbpAnimatedHeader.js"></script>



    <!-- The Bootstrap modal window ..... Opened on button click -->
    <div class="my-modal modal fade" id="myModal" tabindex="-1" role="dialog" aria-hidden="true" >
        <div class="modal-content">
            <div class="close-modal" data-dismiss="modal">
                <div class="lr">
                    <div class="rl">
                    </div>
                </div>
            </div>
            <div class="container">
                <div class="row">
                    <div class="col-lg-8 col-lg-offset-2">
                        <div class="modal-body">
                            <h2>Server Analysis</h2>
                            <hr class="star-light">
                            <br /><br />
                            <img src="images/fluor.jpg" class="img-responsive img-centered" alt="">
                            <br />
                            <p>These are the Server Informations shown in the charts.</p>
                            
                            <!-- The Google Charts -->
                            <div class="list-inline item-details text-center" id="chart_div">
                            </div>
                            <br />
                            <!-- Button for closing the modal window -->
                            <button type="button" class="btn btn-default" data-dismiss="modal" onclick="$(#myModal).modal('hide');"><i class="fa fa-times"></i> Close</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    <!-- End of Modal Window div -->
    </div>

        <!-- JavaScript code -->
        <script type="text/javascript">
            //Javascript function to be invoked when button is clicked
            function openModal() {
                // To show the modal window
                $('#myModal').modal('show');  
            }
        </script>

        <!-- Label which will call the openModal() javascript method -->
        <asp:Label ID="LabelModal" runat="server" Text="Label" ></asp:Label>

        <!-- Hidden Field having the names of all the files selected by the user -->
        <asp:HiddenField ID="file_names" runat="server" />

        <!-- End of form -->
        </form>
    
    <!-- End of container div -->
    </div>


    <!-- Footer -->
    <footer class="text-center">
        <div class="footer-below">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        Copyright &copy; Fluor Daniel India Pvt. Ltd. Website 2016
                    </div>
                </div>
            </div>
        </div>
    </footer>


<!-- End of body -->
</body>

<!-- End of page -->
</html>


